application = ['./lab2_1_v10']
encoding = "cp1251"

[[testSuite]]
    number = 1
    name = 'Тест целых строк'
    input=["Это первая строка."]
    output = ['[\S\s]*Эо первая стрка.\s*']
    timeout = 0.5

[[testSuite]]
    number = 2
    name = 'Тест строк с числами'
    input = ["Прибыль составила 1234 рубля"]
    output = ['[\S\s]*Приыль соствила 1234 руля\s*']
    timeout = 0.5

[[testSuite]]
    number = 3
    name = 'Тест больших строк'
    input = ["Здесь будет длинная строка из разных слов для проверки программы"]
    output = ['[\S\s]*Здсь бует длиная строка из разных слов дя проверки прогаммы\s*']
    timeout = 0.5

[[testSuite]]
    number = 4
    name = 'Тест строки с отрицательными числами'
    input = ["-15 Здесь будет другая длинная строка из разных слов для проверки программы"]
    output = ['[\S\s]*-5 Здсь бует другая длиная строка из разных слов дя проверки прогаммы\s*']
    timeout = 0.5

[[testSuite]]
    number = 5
    name = 'Тест пустых строк'
    input = [""]
    output = ['']
    timeout = 0.5

[[testSuite]]
    number = 6
    name = 'Тест строк с вещественным числом'
    input = ["146.677"]
    output = ['[\S\s]*146677\s*']
    timeout = 0.5
