encoding = "cp1251"
fileDelete = "zoo.dat"

[[testSuite]]
    number = 1
    name = 'Запуск программы с параметрами'
    applicationParameters = ['lab74.exe', 'zoo.dat']
    input = [""]
    output = ['[\S\s]*','[\S\s]*1\) Просмотр данных\s*','2\) Добавление данных\s*','3\) Корректировка данных\s*','4\) Поиск животных по природной зоне\s*',
              '5\) Стоимость содержания животных\s*','6\) Удаление данных\s*','0\) Выход\s*','Введите номер команды:[\S\s]*']
    timeout = 0.5

[[testSuite]]
    number = 2
    name = 'Запуск программы без параметров'
    applicationParameters = ['lab74.exe']
    input = [""]
    output = ['[\S\s]*','[\S\s]*Введите имя файла:[\S\s]*']
    timeout = 0.5

[[testSuite]]
    number = 3
    name = 'Запуск программы без параметров и ввод имени файла'
    applicationParameters = ['lab74.exe']
    input = ["zoo.dat"]
    output = ['[\S\s]*','[\S\s]*Введите имя файла: 1\) Просмотр данных\s*','2\) Добавление данных\s*','3\) Корректировка данных\s*',
    '4\) Поиск животных по природной зоне\s*','5\) Стоимость содержания животных\s*','6\) Удаление данных\s*','0\) Выход\s*',
    'Введите номер команды:[\S\s]*']
    timeout = 0.5

[[testSuite]]
    number = 4
    name = 'Запуск программы c параметрами и добавление корректных данных'
    applicationParameters = ['lab74.exe', 'zoo.dat']
    input = ["2","Волк","Тайга","20","\n"]
    output = ['[\S\s]*','[\S\s]*','[\S\s]*1\) Просмотр данных\s*','2\) Добавление данных\s*','3\) Корректировка данных\s*',
        '4\) Поиск животных по природной зоне\s*','5\) Стоимость содержания животных\s*','6\) Удаление данных\s*','0\) Выход\s*',
        '\s*Введите\s*номер\s*команды:\s*Название\s*животного:\s*Природная\s*зона:\s*Затраты\s*на\s*корм\s*\(за\s*1\s*день\):[\S\s]*']
    timeout = 0.5

[[testSuite]]
    number = 5
    name = 'Запуск программы c параметрами и добавление не корректных данных'
    applicationParameters = ['lab74.exe', 'zoo.dat']
    input = ["2","Волк","Тайга","qwerty","10"]
    output = ['[\S\s]*','[\S\s]*','[\S\s]*1\) Просмотр данных\s*','2\) Добавление данных\s*','3\) Корректировка данных\s*',
            '4\) Поиск животных по природной зоне\s*','5\) Стоимость содержания животных\s*','6\) Удаление данных\s*','0\) Выход\s*',
            '\s*Введите\s*номер\s*команды:\s*Название\s*животного:\s*Природная\s*зона:\s*Затраты\s*на\s*корм\s*\(за\s*1\s*день\):[\S\s]*\s*Затраты\s*на\s*корм\s*\(за\s*1\s*день\):[\S\s]*']
    timeout = 0.5

[[testSuite]]
    number = 6
    name = 'Запуск программы c параметрами и просмотр данных'
    applicationParameters = ['lab74.exe', 'zoo.dat']
    input = ["1"]
    output = ['[\S\s]*','[\S\s]*1\) Просмотр данных\s*','2\) Добавление данных\s*','3\) Корректировка данных\s*',
            '4\) Поиск животных по природной зоне\s*','5\) Стоимость содержания животных\s*','6\) Удаление данных\s*','0\) Выход\s*',
            '\s*Введите\s*номер\s*команды:',
            '|\s*Название животного\s*|\s*Природная зона\s*|\s*Затраты на корм \(за 1 день\\s*||[-+]*]||\s*Волк\s*|\s*Тайга\s*|\s*20.00\s*||[-+]*]||\s*Волк\s*|\s*Тайга\s*|\s*10.00\s*||[-+]*]|[\S\s]*']
    timeout = 0.5

[[testSuite]]
    number = 7
    name = 'Проверка поиска животных по природной зоне'
    applicationParameters = ['lab74.exe', 'zoo.dat']
    input = ["4","Тайга"]
    output = ['[\S\s]*','[\S\s]*','[\S\s]*1\) Просмотр данных\s*','2\) Добавление данных\s*','3\) Корректировка данных\s*',
            '4\) Поиск животных по природной зоне\s*','5\) Стоимость содержания животных\s*','6\) Удаление данных\s*','0\) Выход\s*',
            '\s*Введите\s*номер\s*команды:\s*Природная зона:\s*|\s*Название животного\s*|\s*Природная зона\s*|\s*Затраты на корм \(за 1 день\\s*||[-+]*]||\s*Волк\s*|\s*Тайга\s*|\s*20.00\s*||[-+]*]||\s*Волк\s*|\s*Тайга\s*|\s*10.00\s*||[-+]*]|[\S\s]*',
            '\s*Количество животных природной зоны Тайга:\s*2[\S\s]*']
    timeout = 0.5
