application = ['lab2_1_v3.exe']
encoding = "cp1251"

[[testSuite]]
    number = 1
    name = 'Тест целых строк'
    input=["Это первая строка"]
    output = ['[\S\s]*первая строка\s*']
    timeout = 0.5

[[testSuite]]
    number = 2
    name = 'Тест строк с числами'
    input = ["Прибыль составила 1234 рубля"]
    output = ['[\S\s]*1234\s*']
    timeout = 0.5

[[testSuite]]
    number = 3
    name = 'Тест больших строк'
    input = ["еугмдытвщадыьанвлфйт двлмнугыоатмл еугмдытвщадыьанвлфйтдвлмнугыоатмл слово"]
    output = ['[\S\s]*еугмдытвщадыьанвлфйт\s*']
    timeout = 0.5

[[testSuite]]
    number = 4
    name = 'Тест строки с отрицательными числами'
    input = ["еугмдытвщадыьанвлфйт двлмнугыоатмл еугмдытвщадыьанвлфйтдвлмнугыоатмл слово -666"]
    output = ['[\S\s]*еугмдытвщадыьанвлфйт -666\s*']
    timeout = 0.5

[[testSuite]]
    number = 5
    name = 'Тест пустых строк'
    input = [""]
    output = ['']
    timeout = 0.5

[[testSuite]]
    number = 6
    name = 'Тест строк с вещественными числами'
    input = ["еугмдытвщадыьанвлфйт двлмнугыоатмл еугмдытвщадыьанвлфйтдвлмнугыоатмл слово -666 12.344"]
    output = ['[\S\s]*еугмдытвщадыьанвлфйт -666 12.344\s*']
    timeout = 0.5
