#Copyleft (c) be Aleksey Fedorov
name: My_GitHubActions
env:
  APPLICATION_NAME: "Your file"
  PACKAGE_SHA    : "your-application-sha:${{ github.sha }}"



on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  
  testing:
    
    runs-on: ubuntu-latest
 
    steps:
    
    # Runs a single command using the runners shell
    - name: Запуск на Linux
      run: echo Приветствую Вас в своем Гитхабе!
    - name: Подробнее о приложении
      run: |
        echo "Application name:${{ env.APPLICATION_NAME }}"
        echo "PACKAGE_SHA:${{ env.PACKAGE_SHA }}"
    - name: Гитклон репозитория
      uses: actions/checkout@v1
    
    - name: Просмотр содержимого папки
      run: ls -la
      
   

