#Copyleft (c) be Aleksey Fedorov



name: My_GitHubActions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  
  testing:
    
    runs-on: ubuntu-latest

    
    steps:
    

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Приветствую Вас в своем Гитхабе!

  
